#!/usr/bin/env python3
#
# Prints all PyPi projects which make use of one or all of the
# PyPi trove classifiers avilable for the framework.
#
# installation:
#
# download into $HOME/bin
# chmod u+x get_pypi_projects

import pprint
import xmlrpc.client as xmlrpclib

client = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')

# we want all PyPi projects which have at least one classifier set
trove_classifiers = ["Framework :: Robot Framework", "Framework :: Robot Framework :: Library", "Framework :: Robot Framework :: Tool"]
pypi_projects = []
for tc in trove_classifiers:
    tc_pypi_projects = [p[0] for p in client.browse([tc])]
    pypi_projects += tc_pypi_projects

pprint.pprint(set(pypi_projects))
