name: Awesome-(Ro)Bot

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install gem
        run: gem install awesome_bot
      - name: Check links
        run: |
          awesome_bot README.md --allow-dupe -w robotframework.org,linkedin.com
